server:
  port: 8999

spring:
  data:
    mongodb:
      uri: mongodb://localhost/yangtze_delta_simulator
  servlet:
    multipart:
     max-file-size: 1024MB
     max-request-size: 10240MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${dataStoreDir}
  mvc:
    static-path-pattern: /store/**

#静态资源的映射地址前面部分
staticFilePattern: /store

dataStoreDir: E:/GitProject/YangtzeDataStoreNew
bigFileUploadDir: ${dataStoreDir}/bigFileTemp

dataContainerIpAndPort: geomodeling.njnu.edu.cn/dataTransferServer
managerServerIpAndPort: 222.192.7.75:8084

geoserverUrl: http://172.21.213.92:8089/geoserver
geoserverUserName: admin
geoserverPassword: geoserver


